/*
 * This source file was generated by the Gradle 'init' task
 */
package com.krafta;

import com.krafta.api.FetchResponse;
import com.krafta.api.ListOffsetsRequest;
import com.krafta.api.ListOffsetsResponse;
import com.krafta.broker.Broker;
import com.krafta.client.ClusterClient;
import com.krafta.coord.ClusterCoordService;

import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {
    private static final long SEVEN_DAYS_MS = 7L * 24 * 60 * 60 * 1000;
    private static final long ONE_DAY_MS = 24L * 60 * 60 * 1000;
    private static final String DATA_ROOT = "../data";
    private static final String TOPIC = "orders";

    public static void main(String[] args) throws Exception {
        long now = System.currentTimeMillis();

        ClusterCoordService clusterCoord = new ClusterCoordService();
        Broker broker1 = new Broker(
                DATA_ROOT + "/broker-1", 1024 * 1024, ONE_DAY_MS, SEVEN_DAYS_MS,
                clusterCoord, 1, "broker-1", 5_000
        );
        Broker broker2 = new Broker(
                DATA_ROOT + "/broker-2", 1024 * 1024, ONE_DAY_MS, SEVEN_DAYS_MS,
                clusterCoord, 2, "broker-2", 5_000
        );
        Broker broker3 = new Broker(
                DATA_ROOT + "/broker-3", 1024 * 1024, ONE_DAY_MS, SEVEN_DAYS_MS,
                clusterCoord, 3, "broker-3", 5_000
        );

        broker1.heartbeatCluster(now + 1); //alive brokers
        broker2.heartbeatCluster(now + 1);
        broker3.heartbeatCluster(now + 1);

        broker1.createTopicInCluster(TOPIC, 6); //assigns partitions to brokers(round robin)
        broker2.syncTopicFromCluster(TOPIC);
        broker3.syncTopicFromCluster(TOPIC);

        Map<Integer, Broker> brokerMap = new HashMap<>();
        brokerMap.put(1, broker1);
        brokerMap.put(2, broker2);
        brokerMap.put(3, broker3);
        ClusterClient client = new ClusterClient(clusterCoord, brokerMap);

        System.out.println("Smoke test: static partition owners");
        ClusterCoordService.TopicPlacement placement = clusterCoord.topicPlacement(TOPIC).orElseThrow();
        for (int partition = 0; partition < placement.partitionCount(); partition++) {
            System.out.println("partition=" + partition + " ownerBroker=" + placement.ownerByPartition().get(partition));
        }

        for (int partition = 0; partition < placement.partitionCount(); partition++) {
            String payload = "p" + partition + "-msg1";
            client.produce(TOPIC, partition, payload.getBytes(StandardCharsets.UTF_8));
        }
        client.refreshMetadata();

        System.out.println("\nProducer owner routing check");
        for (int partition = 0; partition < placement.partitionCount(); partition++) {
            int owner = client.ownerBrokerId(TOPIC, partition);
            ListOffsetsResponse latest = client.listOffsets(TOPIC, partition, ListOffsetsRequest.OffsetSpec.LATEST);
            System.out.println("partition=" + partition + " routedToBroker=" + owner + " latestOffset=" + latest.offset());
        }

        System.out.println("\nConsumer fetch from owner brokers");
        for (int partition = 0; partition < placement.partitionCount(); partition++) {
            int owner = client.ownerBrokerId(TOPIC, partition);
            FetchResponse response = client.fetch(TOPIC, partition, 1, 10, 0);
            String value = response.records().isEmpty()
                    ? "<empty>"
                    : new String(response.records().get(0).payload, StandardCharsets.UTF_8);
            System.out.println("partition=" + partition + " fetchedFromBroker=" + owner + " value=" + value);
        }
    }
}
