/*
 * This source file was generated by the Gradle 'init' task
 */
package com.krafta;

import com.krafta.broker.Broker;
import com.krafta.consumer.Consumer;
import com.krafta.exceptions.TopicAlreadyExistsException;
import com.krafta.exceptions.TopicNotFoundException;
import com.krafta.producer.Producer;
import com.krafta.storage.Message;
import com.krafta.storage.Partition;

import java.io.IOException;
import java.util.List;

public class App {

    public static void main(String[] args) throws TopicNotFoundException, TopicAlreadyExistsException,IOException {
        Broker broker = new Broker();
        broker.createTopic("orders",3);
        broker.createTopic("events",3);
//        String root = System.getProperty("user.dir");
//        Partition partition = new Partition( "../data");

        broker.send("orders","msg0 of orders topic");
        broker.send("orders","msg1 of orders topic");
        broker.send("events","msg0 of events topic");
        broker.send("events","msg1 of events topic");
//        Producer producer = new Producer(partition);
//        long offset1 = broker.send("orders","orders topic msg1");
//        long offset2 = producer.send("Welcome to Kafka!");


        List<Partition> ordersPartitions = broker.getPartitions("orders");
        Consumer ordersconsumer = new Consumer("orders",ordersPartitions);
        try {
            ordersconsumer.poll(5);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        List<Partition> eventsPartitions = broker.getPartitions("events");
        Consumer eventsconsumer = new Consumer("events",eventsPartitions);
        try {
            eventsconsumer.poll(5);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }



        // ============= OPTIONAL: Direct Partition Access =============
//        System.out.println("--- Direct Partition Access ---");
//        Partition ordersTopic = broker.topics.get("orders");
//        Message msg = ordersTopic.read(2);
//        System.out.println("Message at offset 2: " + new String(msg.payload));
    }
}
