/*
 * This source file was generated by the Gradle 'init' task
 */
package com.krafta;

import com.krafta.storage.Partition;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
//        String root = System.getProperty("user.dir");
        Partition partition = new Partition( "../data");

        long offset1 = partition.append("Hello Kafka");
        long offset2 = partition.append("Second message");

        System.out.println("Written offsets: " + offset1 + ", " + offset2);
    }
}
